### ISSUE TITLE
500 characters limit when calling XMLStreamReader#getText() after CDATA event

### ISSUE THREAD

**Issue by elrodro83** [FasterXML/woodstox#21]
While the scenario tested in TestXMLStreamReader2#testLongerCData() works correcly, the same 500 chars limit bug (WSTX-211) is still happening with a slight modification. For instance, this test case:

```
    public void testLongerCData2() throws Exception
    {
        String SRC_TEXT =
                "\r\n123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678\r\n"
                          + "<embededElement>Woodstox 4.0.5 does not like this embedded element.  However, if you take\r\n"
                          + "out one or more characters from the really long line (so that less than 500 characters come between\r\n"
                          + "'CDATA[' and the opening of the embeddedElement tag (including LF), then Woodstox will instead\r\n"
                          + "complain that the CDATA section wasn't ended.";
        String DST_TEXT = SRC_TEXT.replace("\r\n", "\n");
        String XML = "<?xml version='1.0' encoding='utf-8'?>\r\n"
                     + "<test><![CDATA[" + SRC_TEXT + "]]></test>";
        // Hmmh. Seems like we need the BOM...
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        bos.write(0xEF);
        bos.write(0xBB);
        bos.write(0xBF);
        bos.write(XML.getBytes("UTF-8"));
        byte[] bytes = bos.toByteArray();
        XMLInputFactory2 f = (XMLInputFactory2) XMLInputFactory.newInstance();
        // important: don't force coalescing, that'll convert CDATA to CHARACTERS
        f.setProperty(XMLInputFactory.IS_COALESCING, Boolean.valueOf(false));

        XMLStreamReader sr = f.createXMLStreamReader(new ByteArrayInputStream(bytes));
        assertTokenType(START_DOCUMENT, sr.getEventType());
        assertTokenType(START_ELEMENT, sr.next());
        assertEquals("test", sr.getLocalName());
        assertTokenType(CDATA, sr.next());
        // This should still work, although with linefeed replacements
        final String text = sr.getText();
        assertEquals("" + text.length(), DST_TEXT, text);
        // assertTokenType(END_ELEMENT, sr.getEventType());
        sr.close();
    }
```

does *sr.next()* followed by *sr.getText()* instead of doing just *sr.getElementText()*.

When running this test case, you will see that only the first 500 characters are read.

This usage id done, for instance, by CXF, in *StaxUtils#copy*

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Just to be sure, which version did you reproduce this with?

**Comment by elrodro83** [comment]
I am using 4.4.1, and reproduced it with the test above on master also.

**Comment by elrodro83** [comment]
Hi @cowtowncoder, did you have a chance to look into this issue?

**Comment by cowtowncoder** [comment]
@elrodro83 Sorry, was out on vacation for last week and half, so not yet. Hoping to catch up on backlog during this week.

**Comment by cowtowncoder** [comment]
Can reproduce with the test included, investigating.

**Comment by cowtowncoder** [comment]
I can see the issue too. Partial segment accepted for CDATA, should not (only relevant for CHARACTERS). Need to figure out proper fix since this is relevant for accessors other that `getText()` as well.

**Comment by cowtowncoder** [comment]
Actually turned out to be easily solved by forcing longer (Integer.MAX_VALUE) limit on one call for finishing CDATA; now passes all old tests, new one.

**Comment by cowtowncoder** [comment]
... although, now does OOME on one of limit tests. Hmmh.

**Comment by cowtowncoder** [comment]
Fixed a problem that may have existed before wrt cdata content limits; now all tests pass, including one for this issue.

**Comment by elrodro83** [comment]
Great! Is there any chance a version can be released with this fix?

**Comment by cowtowncoder** [comment]
@elrodro83 I should be able to do that quite soon, just need to see if there might be other simple fixes to get in; so far this was second fix for 5.0.3.

**Comment by cowtowncoder** [comment]
I just released 5.0.3, should be visible via Maven Central soon. 4 fixes included.

**Comment by elrodro83** [comment]
Just tested with the new version, but still having some problems, Created https://github.com/FasterXML/woodstox/issues/22
